import type { Metadata } from "next";
import "./globals.css";

import DesktopSideNav from "../_components/desktop-sidebar";
import Navbar from "../_components/navbar";
import { SidebarProvider } from "../context/SidebarContextProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
        <SidebarProvider>
    <html lang="en">
      <body
        className={` min-h-screen    `}
      >

        <Navbar
          
        />
       
        <DesktopSideNav/>
        {children}
      </body>
    </html>
    </SidebarProvider>

  );
}
