import type { Metadata } from "next";
import "./globals.css";
import SideNav from "../_components/sidenav";
import DesktopSideNav from "../_components/desktop-sidebar";
import Navbar from "../_components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  pl-[270px] ml-[28px] pt-[64px]`}
      >
        <Navbar/>
        <SideNav />
        <DesktopSideNav/>
        {children}
      </body>
    </html>
  );
}
